import { Rubik } from 'next/font/google'
import PrelineScript from "./components/PrelineScript";
import './globals.css'
import NavBar from './components/navbar';

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body classNameName={rubik.className}>
        <NavBar />      
        {children}
      </body>
      <PrelineScript />
    </html>
  )
}
